// Code generated by "stringer -type=Format"; DO NOT EDIT.

package wav

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PCM-1]
	_ = x[IEEEFloat-3]
	_ = x[ALaw-6]
	_ = x[MuLaw-7]
	_ = x[Extensible-65534]
}

const (
	_Format_name_0 = "PCM"
	_Format_name_1 = "IEEEFloat"
	_Format_name_2 = "ALawMuLaw"
	_Format_name_3 = "Extensible"
)

var (
	_Format_index_2 = [...]uint8{0, 4, 9}
)

func (i Format) String() string {
	switch {
	case i == 1:
		return _Format_name_0
	case i == 3:
		return _Format_name_1
	case 6 <= i && i <= 7:
		i -= 6
		return _Format_name_2[_Format_index_2[i]:_Format_index_2[i+1]]
	case i == 65534:
		return _Format_name_3
	default:
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
